.PHONY: clean All

All:
	@echo "----------Building project:[ ItaliaTour - Debug ]----------"
	@"$(MAKE)" -f  "ItaliaTour.mk"
clean:
	@echo "----------Cleaning project:[ ItaliaTour - Debug ]----------"
	@"$(MAKE)" -f  "ItaliaTour.mk" clean
